package org.ogo.server;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.regex.Pattern;

/**
 * @author 1sand0s
 */
public abstract class AbstractGraphQueryEngine {

  /** The ordinals of this enum can be used to get the correct tokens in a property csv file */
  protected enum PROPERTY_FILE_INDEX {
    PROPERTY_NAME,
    PROPERTY_TYPE,
    PROPERTY_VALUE
  }

  /** Path to where CSV files are generated by native agent MUST BE WITHOUT TRAILING '/' */
  protected String CsvPath = ".";

  /** Precompile pattern to match against lines in [*TAG*]_Neo4JProperties.csv files */
  private final Pattern linePattern =
      Pattern.compile(
              "[a-zA-Z_$]+[a-zA-Z_$0-9]+(,)(string|Bstring|char|Bchar|short|Bshort|int|Bint|long|Blong|float|Bfloat|double|Bdouble)(,)(\\[[\\W|\\S]*])(\\n"
              + ")");

  /** Precompile pattern to match against separators in [*TAG*]_Neo4JProperties.csv files */
  private final Pattern lineSeparatorPattern = Pattern.compile(",");

  /** Precompile pattern to match against value separators in [*TAG*]_Neo4JProperties.csv files */
  private final Pattern lineValueSeparatorPattern = Pattern.compile("x");

  /**
   * @brief Gets all the properties present in [*TAG*]_Neo4JProperties.csv file
   * @author 1sand0s
   * @param dirName Directory where the file is present
   * @param fileName name of the file
   * @param propertyName Names of all the properties present in the file (returned by the function)
   * @param propertyValue Values of all the properties present in the file (returned by the
   *     function)
   * @param propertyType Types of all the properties present in the file (returned by the function)
   * @since 1.0.0
   */
  public void getPropertiesFromFile(
      String dirName,
      String fileName,
      ArrayList<String> propertyName,
      ArrayList<String[]> propertyValue,
      ArrayList<String> propertyType) {
    /* Handle to the file */
    File file = new File(dirName + "/" + fileName);

    /* Check if file exists, not all instances may have primitive fields */
    if (file.isFile() && file.exists()) {
      Scanner scan;
      try {
        scan = new Scanner(file);
        while (scan.hasNext()) {
          String[] tokens = getPropertyFileTokens(scan.nextLine());

          if (tokens == null) return;

          propertyName.add(tokens[PROPERTY_FILE_INDEX.PROPERTY_NAME.ordinal()]);

          /* If the property value is not string then it could potentially be a primitive array
           * which is stored as comma-separated element values in the [*TAG*]_Neo4JProperties.csv file
           * We need to extract each element and cast it into Object type hence the StringTokenizer
           */
          if (!tokens[PROPERTY_FILE_INDEX.PROPERTY_TYPE.ordinal()].equalsIgnoreCase("JSTRING")) {
            StringTokenizer tokens2 =
                new StringTokenizer(tokens[PROPERTY_FILE_INDEX.PROPERTY_VALUE.ordinal()], ",");

            /* Store as string, but we will use PROPERTY_TYPE to cast it appropriately later */
            String[] linePropertyValue = new String[tokens2.countTokens()];
            for (int j = 0; tokens2.hasMoreTokens(); j++)
              linePropertyValue[j] = (tokens2.nextToken());

            propertyValue.add(linePropertyValue);
          } else {
            propertyValue.add(new String[] {tokens[PROPERTY_FILE_INDEX.PROPERTY_VALUE.ordinal()]});
          }

          /* store property type so we can cast the property values appropriately */
          propertyType.add(tokens[PROPERTY_FILE_INDEX.PROPERTY_TYPE.ordinal()]);
        }
      } catch (FileNotFoundException e) {
        System.out.println(
            "Error : File " + file.getName() + " not found in path " + file.getPath());
        System.out.println("Unable to create properties described in " + file.getName());
      }
    }
  }

  /**
   * @brief Extracts tokens from a line in the [*TAG*]_Neo4JProperties.csv file
   *     <p>Example : tokens : str , [UTAUSTIN] , string lexemes : PROPERTY_NAME | PROPERTY_VALUE |
   *     PROPERTY_TYPE
   * @author 1sand0s
   * @param line String corresponding to a line in [*TAG*]_Neo4JProperties.csv file
   * @return String[] Array of tokens extracted from the line
   * @since 1.0.0
   */
  public String[] getPropertyFileTokens(String line) {

    String[] tokens = lineSeparatorPattern.split(line, 3);

    if (tokens == null) return null;

    if (tokens[1].equals("JCHAR")) {
      tokens[2] = (char) (Integer.parseInt(tokens[2])) + "";
    }

    if (!tokens[1].equals("JSTRING")) return tokens;

    String[] valueTokens = lineValueSeparatorPattern.split(tokens[2]);
    tokens[2] = "";

    /* First element of valueTokens is going to be empty*/
    for (int j = 1; j < valueTokens.length; j++) {
      tokens[2] += ((char) Byte.parseByte(valueTokens[j]));
    }
    return tokens;
  }
}
