# Default global log level (SEVERE > WARNING > INFO > CONFIG > FINE > FINER > FINEST)
.level=WARNING

# Send logs to the console.
handlers=java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level=WARNING
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

# Package-specific override for org.ogo.
org.ogo.level=WARNING
