# Clear Neo4j data after each run when not in-memory.
clearDatabase=true
# Controls if OGO ran in mem or neo mode
inMemory=false
maven.compiler.source=21
maven.compiler.target=21
project.build.sourceEncoding=UTF-8
# Defines the port used for Java RMI communication between OGO and the Neo4j server JVM.
rmiPort=2095