package org.ogo.bridge;

import java.rmi.Remote;
import java.rmi.RemoteException;
import java.util.ArrayList;

/**
 * @author 1sand0s
 */
public interface AbstractGraphQueryInterface extends Remote {

  /**
   * @brief Set up the database
   * @author 1sand0s
   * @since 1.0.0
   */
  void setup() throws RemoteException;

  /**
   * @brief Create Graph Nodes
   * @author 1sand0s
   * @since 1.0.0
   */
  void createNodes() throws RemoteException;

  /**
   * @brief Create Relations between nodes
   * @author 1sand0s
   * @since 1.0.0
   */
  void createRelations() throws RemoteException;

  /**
   * @brief Executes the Cypher query contained in the string cQuery
   * @author 1sand0s
   * @param queryString Query String
   * @return ArrayList<Object> Returns the result of the query
   * @since 1.0.0
   */
  ArrayList<Object> query(String queryString) throws RemoteException;

  /**
   * @brief Sets the path from where CSV files generated by native agent are read
   * @author 1sand0s
   * @param path Path where the native agent writes the Csv files
   * @since 1.0.0
   */
  void setPath(String path) throws RemoteException;

  /**
   * @brief Sets the path from where CSV files generated by native agent are read
   * @author 1sand0s
   * @since 1.0.0
   */
  String getPath() throws RemoteException;

  /**
   * @brief Remove all nodes and relations from database before importing new object graph.
   *     (Possibly update the database instead ?)
   * @author 1sand0s
   * @since 1.0.0
   */
  void clearDatabase() throws RemoteException;

  /**
   * @brief Shutdown database
   * @author 1sand0s
   * @since 1.0.0
   */
  void shutDown() throws RemoteException;
}
